### PR TITLE
blog post hackathon 

### PR DESCRIPTION
**Pull request by afourmy**
This is a brief introduction to the project I created during the hackathon. I renamed the project because I added a lot of new functions for network visualization, but in this post I focus on the network automation part.
I have a few videos in the post and I didn't know where to put them, so I stored them in a repository on my github but I can also upload them somewhere in this repository if you tell me where (11mb in total, hope it's not too big)

### CODE REVIEW

**Comment by ogenstad** [comment]
This is currently failing the test due to the short name of the slug. I.e. it's named "eNMS-presentation", this is in place to avoid too generic names for the blog posts which might conflict with future posts or pages. The other failure in the tests should be fixed by #73.

I think it would be better to have the images locally here. If you create a 2018 directory under /images. Then just prefix the image names with the same slug as is used for this post.

**Comment by afourmy** [comment]
Actually I also noticed that i added the article itself under /2017, I should probably create /2018 under /_posts as well. I'll make the change for the images soon. What you call slug is the name of the .md file right ? What is the minimal length ?
Thanks

**Comment by ogenstad** [comment]
Ah yes, please place it under 2018 :)

This is the test:
https://github.com/napalm-automation/napalm-automation.github.io/blob/master/tests/test_site.py#L22-L29

Given your filename `2018-01-11-eNMS-presentation.md` the first part gets used as the date so the slug would be `enms-presentation` which is two words. The tests requires three or more words, i.e. one more.

**Comment by afourmy** [comment]
I did the changes but apparently it's still failing. For the image prefix, there is no character between the slug and the actual name, I wasn't sure whether to put a dash, underscore or something else.

**Comment by ogenstad** [comment]
It was just failing because #73 hadn't been merged, I've done that now and restarted the tests for this PR.

**Comment by ogenstad** [comment]
Regarding the images, it would probably be easier to read with some character between the slug and the actual name. What it is isn't really important, that is mostly just to give an idea of which images go with which post, but there hasn't been that many posts.

It looks like you're still loading the images of the Github url though.

**Comment by afourmy** [comment]
LGTM now

**Review by mirceaulinic — APPROVED** [review]

**Pull request merged**
