### PR TITLE
add Linode quote

### PR DESCRIPTION
**Pull request by wasabi222**

### CODE REVIEW

**Comment by dbarrosop** [comment]
oh, nice! thanks for this :D

**Comment by ogenstad** [comment]
Nice quote! This looks good to me.

@wasabi222, the only question I have is regarding the org_logos you added? Was the intention to add Linode as a company under the "Trusted by" section? (That's currently where the logos for the different companies are used). If that was the intention the ones named whitespace have the same 900x600 dimensions but the they have whitespace around them so they won't be too close together. If the intention was to add Linode to that section I can resize that part later.

**Comment by wasabi222** [comment]
Hi @ogenstad, that was my intention to add Linode as well. I didn't really understand the whitespace part so I just uploaded the same image twice with the different names, but feel free to resize. Thanks!

**Comment by ogenstad** [comment]
@wasabi222, that sounds great! Basically it's just so that the logos doesn't blend into each other. The Linode part needs to be added to https://github.com/napalm-automation/napalm-automation.github.io/blob/master/_data/user_orgs.yml. If I have your permission I can do that in a separate PR and swap out one of the logo files?

If so I'll write this in the about Linode section, let me know if you would rather see something different.
>Linode provides cloud hosting for you. Instantly deploy an SSD cloud server running with your choice of Linux distro, resources, and node location.

**Comment by wasabi222** [comment]
@ogenstad Sounds great! Go for it :+1:

**Comment by ogenstad** [comment]
@wasabi222, thanks. I created PR #58 with the resized logo and data to add Linode as a NAPALM user. Do you want to take a look at it, or is it ok if we merge that PR?

**Pull request merged**
