### PR TITLE
Added yang post

### PR DESCRIPTION
**Pull request by dbarrosop**

### CODE REVIEW

**Comment by ogenstad** [comment]
Perhaps use all lowercase in the url?

**Comment by dbarrosop** [comment]
What did I do wrong now? :P

**Comment by ogenstad** [comment]
:) I wouldn't call it wrong, but the url would be /YANG-for-dummies/ just thought that it might be cleaner if everything was lowercase i.e. /yang-for-dummies/.

**Comment by dbarrosop** [comment]
But then the title is going to be lowercase as well, isn't it? Shouldn't we just enforce that the URL is lowercase regardless of the title?

**Comment by ogenstad** [comment]
I can create a test for that too. But the url is picked from the filename not the title within the post.

**Comment by dbarrosop** [comment]
> I can create a test for that too. But the url is picked from the filename not the title within the post.

instead of a test, can it be lowered? I will change the filename though

**Comment by ogenstad** [comment]
I can check, can perhaps be done through some filter.

**Pull request merged**
