### PR TITLE
Added napalm-ansible post

### PR DESCRIPTION
**Pull request by dbarrosop**

### CODE REVIEW

**Comment by ogenstad** [comment]
@dbarrosop, regarding our discussion about url structure on the site. This post would currently get the slug /napalm-ansible/. So if that slug is to be used later the filename of this post should be changed to something like `2017-08-07-installing-napalm-ansible.md`.

I still think this looks cleaner than prefixing everything with /blog/ or /news/, but this would be the downside, i.e. that you have to consider which urls you might want to use for something else in the future.

**Comment by dbarrosop** [comment]
can we add a check somehow to verify the slug for the blog post is at least 4 words?

**Comment by dbarrosop** [comment]
good catch btw!

**Comment by dbarrosop** [comment]
@ktbyers do you want to review and add your changes here?

**Comment by ogenstad** [comment]
Sure, currently when the tests are run a json file containing all the posts and pages are created, it looks something like below.

So we can just add an entry to the py.test run which reads the json file and warns if entries with the content_type "post" has more than four words. And also setup an exception list so it's possible to override those checks if someone needs to. Perhaps three words would be enough?

```
~/src/websites/napalm-automation.github.io (napalm_users ✘)✹✭ ᐅ cat _site/site-validation.json
{

  "_posts/2017/2017-07-20-reunification.md": {
      "content_type": "post",
      "title": "Reunification",
      "title_length": 13,
      "url": "/reunification/",
      "description": "Drivers will be merged soon. Do you want to know more?",
      "description_length": 54,
      "header_teaser": ""
  },

  "_posts/2017/2017-07-17-hello-world.md": {
      "content_type": "post",
      "title": "Hello World",
      "title_length": 11,
      "url": "/hello-world/",
      "description": "Welcome to the new Napalm automation website, this site will be the base of all the information around the project.",
      "description_length": 115,
      "header_teaser": ""
  },

  "_profiles/dbarrosop.md": {
      "content_type": "collection",
      "title": "David Barroso",
      "title_length": 13,
      "url": "/dbarrosop/",
      "description": "About David Barroso",
      "description_length": 19,
      "header_teaser": ""
  },

[...]  
```

**Comment by dbarrosop** [comment]
That sounds great :) yeah three words is probably fine.

**Pull request merged**
