### PR TITLE
Add about section

### PR DESCRIPTION
**Pull request by ogenstad**
Another example for the about page. #30 

Again, like the other example the images on this one would need to be changed to have better alignment.

### CODE REVIEW

**Comment by ogenstad** [comment]
Ready for review.

Fixes #30

(The currently failing Travis tests are link failures probably some current issue between Travis and Read the Docs and can be ignored.)

**Comment by dbarrosop** [comment]
Where are the branches with the other examples? Couldn't find them.

The title should probably go away, at least for now. Everybody in there should be "core" (for now at least while we fix the gamification part) and the titles could be a bit controversial so let's leave that outside for the time being.

Shouldn't we add a "short bio" in the profile instead of having yet another file with profiles?

**Review by dbarrosop — COMMENTED** [review]
Where are the branches with the other examples? Couldn't find them.

The title should probably go away, at least for now. Everybody in there should be "core" (for now at least while we fix the gamification part) and the titles could be a bit controversial so let's leave that outside for the time being.

Shouldn't we add a "short bio" in the profile instead of having yet another file with profiles?

**Comment by ogenstad** [comment]
I removed the other branches, thought you didn't want them. Should I push them up again?

You mean "meet the team" instead of "meet the core team"?

Regarding the short bio, it picks up the text from authors.yml. I.e.
https://github.com/napalm-automation/napalm-automation.github.io/blob/master/_data/authors.yml#L4 I only wrote those short bios as examples but they could be longer.

When you write a blog post that will also be linked to the profile page and my idea was that if you have written a few blog posts they could also show up on your own profile page. Also the profile page could be more of a presentation. But for longer texts one of the other profile designs might be better for the /about/ page.

**Comment by dbarrosop** [comment]
I mean we should get rid of this:

`   title       : "Creator, Core Developer"`

At least for now (feel free to just comment the bit in the template if you want to).

Regarding the bio, what I meant is that having `profiles` and `authors` feels a bit redundant but feel free to ignore me :P

**Comment by ogenstad** [comment]
Removed the title.

Anything else? :)

**Comment by dbarrosop** [comment]
No, sorry for being nitpicky.

Thanks a lot :D

**Comment by ogenstad** [comment]
Any additional thoughts about this?

**Comment by dbarrosop** [comment]
No, not really. I suggest to go ahead and change if needed in the future. No need to delay things anymore.

**Pull request merged**
